structure(list(url = "https://datacatalog.worldbank.org/services/session/token", 
    status_code = 200L, headers = structure(list(date = "Wed, 21 Feb 2018 20:24:19 GMT", 
        server = "Apache/2.2.15 (Red Hat)", `x-powered-by` = "PHP/5.6.30", 
        expires = "Sun, 19 Nov 1978 05:00:00 GMT", `cache-control` = "no-cache, must-revalidate", 
        `x-content-type-options` = "nosniff", vary = "Accept-Encoding,User-Agent", 
        `content-encoding` = "gzip", `content-length` = "63", 
        connection = "close", `content-type` = "text/plain;charset=UTF-8"), .Names = c("date", 
    "server", "x-powered-by", "expires", "cache-control", "x-content-type-options", 
    "vary", "content-encoding", "content-length", "connection", 
    "content-type"), class = c("insensitive", "list")), all_headers = list(
        structure(list(status = 200L, version = "HTTP/1.1", headers = structure(list(
            date = "Wed, 21 Feb 2018 20:24:19 GMT", server = "Apache/2.2.15 (Red Hat)", 
            `x-powered-by` = "PHP/5.6.30", expires = "Sun, 19 Nov 1978 05:00:00 GMT", 
            `cache-control` = "no-cache, must-revalidate", `x-content-type-options` = "nosniff", 
            vary = "Accept-Encoding,User-Agent", `content-encoding` = "gzip", 
            `content-length` = "63", connection = "close", `content-type` = "text/plain;charset=UTF-8"), .Names = c("date", 
        "server", "x-powered-by", "expires", "cache-control", 
        "x-content-type-options", "vary", "content-encoding", 
        "content-length", "connection", "content-type"), class = c("insensitive", 
        "list"))), .Names = c("status", "version", "headers"))), 
    cookies = structure(list(domain = c("datacatalog.worldbank.org", 
    "#HttpOnly_.datacatalog.worldbank.org"), flag = c(FALSE, 
    TRUE), path = c("/", "/"), secure = c(FALSE, TRUE), expiration = structure(c(Inf, 
    1539244497), class = c("POSIXct", "POSIXt")), name = c("datacatalog.sfarm", 
    "SSESSea72a4c978dd1670e2b2d8df72f13a23"), value = c("REDACTED", 
    "REDACTED")), .Names = c("domain", "flag", "path", "secure", 
    "expiration", "name", "value"), row.names = c(NA, -2L), class = "data.frame"), 
    content = as.raw(c(0x65, 0x50, 0x6e, 0x35, 0x78, 0x78, 0x31, 
    0x5f, 0x6e, 0x4e, 0x2d, 0x71, 0x50, 0x62, 0x76, 0x4f, 0x35, 
    0x57, 0x36, 0x46, 0x63, 0x6c, 0x45, 0x79, 0x56, 0x75, 0x75, 
    0x6f, 0x49, 0x6c, 0x61, 0x5a, 0x6b, 0x6c, 0x64, 0x66, 0x63, 
    0x4b, 0x66, 0x63, 0x54, 0x6c, 0x41)), date = structure(1519244659, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = structure(c(0, 1e-06, 
    1e-06, 0.016, 0.562, 0.562), .Names = c("redirect", "namelookup", 
    "connect", "pretransfer", "starttransfer", "total")), request = structure(list(
        method = "POST", url = "https://datacatalog.worldbank.org/services/session/token", 
        headers = structure(c("", "application/json", "SSESSea72a4c978dd1670e2b2d8df72f13a23=eFbT3WYrttAtQnTvnaVoLZt-lEZFKryrSYD5PVVj7cI"
        ), .Names = c("Content-Type", "Accept", "Cookie")), fields = NULL, 
        options = structure(list(useragent = "libcurl/7.56.1 r-curl/3.1 httr/1.3.1", 
            cainfo = "C:/PROGRA~1/R/R-34~1.3/etc/curl-ca-bundle.crt", 
            post = TRUE, postfieldsize = 0L), .Names = c("useragent", 
        "cainfo", "post", "postfieldsize")), output = structure(list(), class = c("write_memory", 
        "write_function"))), .Names = c("method", "url", "headers", 
    "fields", "options", "output"), class = "request")), .Names = c("url", 
"status_code", "headers", "all_headers", "cookies", "content", 
"date", "times", "request"), class = "response")
